// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNcIpIuPGC1a3a9pqjl5L-oycn-4pIBOo',
    appId: '1:452950992890:web:5aa5be9d0d624ac41a2643',
    messagingSenderId: '452950992890',
    projectId: 'sparkler-e31dd',
    authDomain: 'sparkler-e31dd.firebaseapp.com',
    storageBucket: 'sparkler-e31dd.appspot.com',
    measurementId: 'G-LSMLBZ99P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBObVBSWaZX9JkNqGgvK2wi1QLfpLv17NI',
    appId: '1:452950992890:android:d6d3190d89a001c81a2643',
    messagingSenderId: '452950992890',
    projectId: 'sparkler-e31dd',
    storageBucket: 'sparkler-e31dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKsdSkg2YWMJN_v_SDUWHLEPlkJKFjhFk',
    appId: '1:452950992890:ios:0e7ae0e4b09d025e1a2643',
    messagingSenderId: '452950992890',
    projectId: 'sparkler-e31dd',
    storageBucket: 'sparkler-e31dd.appspot.com',
    iosBundleId: 'com.example.sparkler',
  );
}
